contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #createpanelofnormals channel"
    url: https://nfcore.slack.com/channels/createpanelofnormals
    about: Discussion about the nf-core/createpanelofnormals pipeline
